# Generated by Django 5.2.3 on 2025-06-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_alter_officialregistration_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='officials_profile_picture/'),
        ),
    ]
